### ISSUE TITLE
目前完善度如何

### ISSUE THREAD

**Issue by magic007** [Youjingyu/vue-hap-tools#1]
大哥，佩服你，写了半个月快应用，终于把我们的SDK，推出了快应用版本， 然后想写个demo出来看看，发觉太困难， css很多属性不支持， 标签也是不按常理来。例如div不能包含div，text也不能随便包含text 多层。 你的已知问题，整理的很好，觉得官方就应该整理一个这种说明。请问下目前这个vue-hap-tools 完善度如何，除了你那个demo，有基于这个开发的线上项目吗？
<img width="50" alt="7777" src="https://user-images.githubusercontent.com/2484137/40714798-3179990a-6436-11e8-863c-99ced39229ec.png">

**Comment by Youjingyu** [comment]
@magic007 不好意思，回复晚了。快应用的vue语法、css支持情况可以说是web的子集，只要面向这个子集来开发，vue-hap-tools是可以做到代码复用的。至于vue-hap-tools的完善度，已达成我们的预期，后期可能会实现vue的高级特性，比如混入、自定义指令、Vue.use等，个人认为，对于不太复杂的应用，这些高级特性可能也并不那么刚需，另外，还需要完善对vue生态的兼容。
至于线上应用，你可以在小米、华为应用商店中搜索新浪新闻，会提示直达版本，无需安装，可以直接打开

**Comment by magic007** [comment]
好的，感谢，请问新浪新闻是您写的吗？

**Comment by Youjingyu** [comment]
@magic007 同事写的
