### ISSUE TITLE
你好，使用过程中并不顺利啊。

### ISSUE THREAD

**Issue by Yunnathai** [Youjingyu/vue-hap-tools#2]
你好，使用过程中并不顺利啊。

vue的能跑起来，快应用 装了后就 崩溃，打开失败。

无法debug

**Comment by Youjingyu** [comment]
@jamninetyfive 是[快应用调试器](https://www.quickapp.cn/docCenter/post/69)本身崩溃，还是用调试器扫码执行本地代码后崩溃？
是否是用支持快应用的安卓手机（比如华为、小米）安装的调试器？

**Comment by Yunnathai** [comment]
魅族手机调试器，扫码后本地代码崩溃，显示出现错误，有办法debug么

**Comment by Yunnathai** [comment]
因为我们现在已经有一款完整的vue应用
我的做法是直接移植代码到 你到工具。
但是跑不起来。

**Comment by Youjingyu** [comment]
@jamninetyfive 你按照vue-hap-tools的文档运行demo能成功吗？也有可能是调式工具版本、以及手机原因，我们还是建议用小米、华为测试，他们的快应用成熟些。另外，这个工具还是比较推荐在开发阶段用，而不是转换已有项目。对于已有项目肯定是需要做一定的修改的，比如同类工具，美团的[mpvue](http://mpvue.com/)应该也不能做到无痛转换已有项目
