### ISSUE TITLE
如何在script中引css

### ISSUE THREAD

**Issue by pigjane** [Youjingyu/vue-hap-tools#3]
```
<script>
import "../../css/index.css";
export default {
  data() {
    return {
    };
  }
};
</script>
```

你好，这个框架很棒，但是也遇到了问题。
如果像以上代码引用`css`会报错，请问怎么解决？`css`和`pages`同一级别目录

**Comment by Youjingyu** [comment]
为什么不像下面这样写？
```html
<script>
export default {
  data() {
    return {
    };
  }
};
</script>
<style>
@import "../../css/index.css";
</style>
```

**Comment by pigjane** [comment]
@Youjingyu 
这样写是可以的，但是我的项目框架中有一个`rem2rpx`loader，如果把样式放到`style`里引，`rem`转不了`rpx`，所以很蛋疼

**Comment by Youjingyu** [comment]
@pigjane  vue-hap-tools添加了rem转px的功能，参考这里[样式](https://github.com/Youjingyu/vue-hap-tools/blob/master/docs/doc.md#%E6%A0%B7%E5%BC%8F)  
针对web的打包，css放在style里，rem2rpx loader应该也可以转的吧，rem2rpx不可能要求必须在js里引入，可能配置没对，你可以参考vue-cli模板工程的配置

**Comment by pigjane** [comment]
@Youjingyu 
那也不可能要求必须在`style`里引，对吧- -

**Comment by Youjingyu** [comment]
@pigjane 由于快应用本身打包工具的限制，不能处理在js中引入的css
个人觉得在style中引入比较符合vue的使用习惯   
在js中引入css在react中用得多些

**Comment by Youjingyu** [comment]
@pigjane 一个比较笨的方式是，打包到web的时候，你把css移动到script标签，打包快应用的时候，将css移动到style标签

**Comment by pigjane** [comment]
@Youjingyu 我现在是用你的注释，把js部分的引用放进去了

**Comment by Youjingyu** [comment]
@pigjane 机智  这个方式可以
