### ISSUE TITLE
为什么不跟mpvue一样，用webpack插件来做转译呢，这样就可以不用限制目录结构了

### ISSUE THREAD

**Issue by dyw934854565** [Youjingyu/vue-hap-tools#4]

**Comment by Youjingyu** [comment]
因为我们基于快应用官方脚手架[hap-toolkit](https://doc.quickapp.cn/tutorial/getting-started/build-environment.html)来做的，hap-toolkit有目录限制
我们也考虑过mpvue的模式，如果采用mpvue的模式，随官方升级的成本比较高
